# Generated by Django 3.2.8 on 2021-12-17 23:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='categorie',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='auctions.categories'),
        ),
        migrations.AlterField(
            model_name='bids',
            name='time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 12, 17, 23, 18, 32, 791878)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 17, 23, 18, 32, 791878)),
        ),
    ]
