# Generated by Django 3.2.8 on 2021-12-18 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20211217_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='title',
            field=models.CharField(max_length=23),
        ),
        migrations.AlterField(
            model_name='bids',
            name='time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 12, 18, 18, 18, 51, 796531)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 18, 18, 18, 51, 796531)),
        ),
    ]
