# Generated by Django 3.2.8 on 2021-12-18 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20211218_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 12, 18, 19, 28, 58, 850590)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 18, 19, 28, 58, 851589)),
        ),
    ]
