# Generated by Django 3.2.8 on 2021-12-19 23:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20211218_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='bids',
            name='time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 12, 19, 23, 53, 48, 423717)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 19, 23, 53, 48, 423717)),
        ),
    ]
