# Generated by Django 3.2.8 on 2021-12-20 00:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20211219_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 12, 20, 0, 3, 38, 661761)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 20, 0, 3, 38, 662761)),
        ),
    ]
